version: '3.9'

services:
    telegram_bot:
        container_name: TelegramBot
        image: telegram_bot
        build: .
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
        ports:
            - "127.0.0.1:443:443"
        volumes:
            - ./logs:/~/TelegramBotDockerTmpl/logs
        restart: on-failure
        networks:
            - first_network
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
    redis:
        image: "redis:alpine"
        ports:
            - "127.0.0.1:6379:6379"
        networks:
            - second_network
        deploy:
            resources:
                limits:
                    cpus: '0.10'
                    memory: 128M
                reservations:
                    cpus: '0.05'
                    memory: 64M
networks:
    first_network:
        driver: bridge
    second_network:
        driver: bridge