version: '3.9'

services:

    telegram_bot:
        container_name: TelegramBot
        image: telegram_bot

        build: .

        environment:
            - BOT_TOKEN=${BOT_TOKEN}

        ports:
            - "443:443"

        volumes:
          - ./logs:/~/TelegramBotDockerTmpl/logs

        restart: on-failure

    redis:
      image: "redis:alpine"